name: .NET Test Automation Pipeline

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '0 3 * * 1'  # Runs every Monday at 03:00 UTC
    - cron: '*/25 * * * *'  # Runs every 25 minutes
  workflow_dispatch:  # Allows manual execution
    inputs:
      driver:
        description: "Select the browser for UI tests"
        required: true
        default: "Chrome"
        type: choice
        options:
          - Chrome
          - Firefox
          - MSEDGE
      environment:
        description: "Select the test environment (QA, Dev, Prod)"
        required: false
        default: "QA"
        type: choice
        options:
          - QA
          - Prod
      headless:
        description: "Select headless"
        required: false
        default: false
        type: choice
        options:
          - "true"
          - "false"

jobs:
  api-tests:
    name: Run API Tests
    runs-on: windows-latest  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: |
          cd "Selenium WebDriver.Tests"
          dotnet restore "Selenium WebDriver.sln"

      - name: Run API Tests
        working-directory: ./Selenium WebDriver.Tests
        run: |
          dotnet test "Selenium WebDriver.Test.csproj" --filter "TestCategory=API" --logger "trx;LogFileName=API_TestResults.trx"

      - name: Upload API Test Results
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: TestResults/API_TestResults.trx

  ui-tests:
    name: Run UI Tests
    needs: api-tests  # UI runs after API, but still runs if API fails
    runs-on: windows-latest
    env:
      TEST_ENV: ${{ github.event_name == 'pull_request' && 'QA' || github.event.inputs.environment }}
      DRIVER: ${{ github.event_name == 'pull_request' && 'Chrome' || github.event.inputs.driver }}
      HEADLESS: ${{ github.event_name == 'pull_request' && 'false' || github.event.inputs.headless }}
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: |
          cd "Selenium WebDriver.Tests"
          dotnet restore "Selenium WebDriver.sln"

      - name: Run UI Tests
        working-directory: ./Selenium WebDriver.Tests
        run: >
          dotnet test "Selenium WebDriver.Test.csproj" 
          --filter "TestCategory=UI"
          --% --settings:TestData/TestDataResources/settings.${{ env.TEST_ENV }}.runsettings
          -- TestRunParameters.Parameter(name="driver", value="${{ env.DRIVER }}")
          -- TestRunParameters.Parameter(name="headless", value="${{ env.HEADLESS }}")
        continue-on-error: true

      - name: Upload UI Test Results
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-results
          path: TestResults/UI_TestResults.trx

      - name: Upload Failed Test Screenshots
        uses: actions/upload-artifact@v4
        with:
          name: FailedTestScreenshots
          path: |
            Selenium WebDriver.Tests/bin/Debug/net8.0/FailedTestScreenshots/*.png
          retention-days: 7
