name: .NET Test Automation Pipeline

on:
  pull_request:
    branches:
     - APITesting
  schedule:
    - cron: '0 3 * * 1'  # Runs every Monday at 03:00 UTC
    - cron: '*/25 * * * *'  # Runs every 25 minutes
  workflow_dispatch:  # Allows manual execution

jobs:
  api-tests:
    name: Run API Tests
    runs-on: windows-latest  
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Run API Tests
        run: |
          dotnet test "Selenium WebDriver.Test.csproj" --filter "TestCategory=API" --logger "trx;LogFileName=API_TestResults.trx"

      - name: Upload API Test Results
        uses: actions/upload-artifact@v4
        with:
          name: api-test-results
          path: TestResults/API_TestResults.trx

  ui-tests:
    name: Run UI Tests
    needs: api-tests  # UI runs after API, but still runs if API fails
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x'

      - name: Restore Dependencies
        run: dotnet restore

      - name: Run UI Tests
        run: |
          dotnet test "Selenium WebDriver.Test.csproj" --filter "TestCategory=UI" --logger "trx;LogFileName=UI_TestResults.trx"

      - name: Upload UI Test Results
        uses: actions/upload-artifact@v4
        with:
          name: ui-test-results
          path: TestResults/UI_TestResults.trx

      - name: Upload Screenshots (if available)
        uses: actions/upload-artifact@v4
        with:
          name: ui-screenshots
          path: Screenshots/
          if-no-files-found: ignore  # Avoid errors if no screenshots exist


  
